theme = "gruvdark"


[editor]
color-modes = true
line-number = "relative"
insert-final-newline = true
auto-format = true
rulers = [120]
# Resolve true color detection problems (e.g. on Linux in Windows WSL2)
# such as the error, "theme: theme requires true color support".
true-color = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true
character = "┊"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
  "separator",
  "version-control"
]
mode = { normal = "🏄 NORMAL", insert = "👉 INSERT", select = "🔍 SELECT" }
separator = " "


[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
tab = "all"
nbsp = "all"

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"
# Ctrl+g to launch lazygit inside a scratch buffer
C-g = [
    ":write-all",               # Save all opened buffers
    ":new",                     # Open a new empty buffer
    ":insert-output lazygit",   # Run lazygit command and insert output in buffer
    ":redraw",                  # Redraw the screen
]

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
